//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// Dx12MSLib.rc で使用
//
#define SHADERID_BILLBOARD_VS		101
#define SHADERID_BILLBOARD_PS		102
#define SHADERID_BILLBOARD_GS		103
#define SHADERID_FBXNORMALMAP_VS	104
#define SHADERID_FBXNORMALMAP_PS	105
#define SHADERID_FBXNORMALMAP_GS	106
#define SHADERID_FBX_VS				107
#define SHADERID_FBX_PS				108
#define SHADERID_FBX_GS				109
#define SHADERID_IMAGE3D_VS			110
#define SHADERID_IMAGE3D_PS			111
#define SHADERID_IMAGE3D_GS			112
#define SHADERID_IMAGE_VS			113
#define SHADERID_IMAGE_PS			114
#define SHADERID_IMAGE_GS			115
#define SHADERID_NORMALMAP_VS		116
#define SHADERID_NORMALMAP_PS		117
#define SHADERID_NORMALMAP_GS		118
#define SHADERID_PMDBASIC_VS		119
#define SHADERID_PMDBASIC_PS		121
#define SHADERID_PMDBASIC_GS		122
//#define SHADERID_PMDTOON_VS		123
//#define SHADERID_PMDTOON_PS		124
//#define SHADERID_PMDTOON_GS		125
//#define SHADERID_PRIMITIVE2D		126
#define SHADERID_PRIMITIVE3D_VS		127
#define SHADERID_PRIMITIVE3D_PS		128
#define SHADERID_PRIMITIVE3D_GS		129
#define SHADERID_SKELETON_VS		130
#define SHADERID_SKELETON_PS		131
#define SHADERID_SKYBOX				132
#define SHADERID_WIREFRAME			133






// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
